sudo: required
services:
  - docker

before_install:
  - docker build -t paedelm/frontend-test -f Dockerfile.dev .

script:
  - docker run paedelm/frontend-test npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "frontend-react"
  env: "FrontendReact-env"
  bucket_name: "elasticbeanstalk-us-east-1-907071471153"
  bucket_path: "frontend-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"